#!/usr/bin/env python3
"""
Noctalia-style logout menu with horizontal card layout
Colors are loaded from logout-menu-colors.py (generated by switch-theme.sh)
"""

import gi

gi.require_version("Gtk", "3.0")
gi.require_version("Gdk", "3.0")
import os
import subprocess
import sys

from gi.repository import Gdk, Gtk

# ─── Load theme colors ───
_colors_dir = os.path.dirname(os.path.abspath(__file__))
_colors_file = os.path.join(_colors_dir, "logout-menu-colors.py")
if os.path.exists(_colors_file):
    with open(_colors_file) as _f:
        exec(_f.read())
else:
    # Fallback defaults
    BG_COLOR = "#1d2021"
    CARD_BG = "#282828"
    CARD_HOVER = "#3c3836"
    TEXT_COLOR = "#ebdbb2"
    ACCENT_COLOR = "#d79921"
    ERROR_COLOR = "#fb4934"
    BORDER_COLOR = "#504945"

ACTIONS = [
    {
        "icon": "system-lock-screen",
        "label": "Lock",
        "cmd": "loginctl lock-session",
        "color": ACCENT_COLOR,
        "key": "1",
    },
    {
        "icon": "system-reboot",
        "label": "Reboot",
        "cmd": "systemctl reboot",
        "color": ACCENT_COLOR,
        "key": "2",
    },
    {
        "icon": "system-log-out",
        "label": "Logout",
        "cmd": "mango exit",
        "color": ACCENT_COLOR,
        "key": "3",
    },
    {
        "icon": "system-shutdown",
        "label": "Shutdown",
        "cmd": "systemctl poweroff",
        "color": ERROR_COLOR,
        "key": "4",
    },
    {
        "icon": "system-reboot",
        "label": "Reboot to UEFI",
        "cmd": "systemctl reboot --firmware-setup",
        "color": ACCENT_COLOR,
        "key": "5",
    },
]


class LogoutCard(Gtk.EventBox):
    def __init__(self, action, window):
        super().__init__()
        self.action = action
        self.window = window

        # Card container
        card = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=12)
        card.set_halign(Gtk.Align.CENTER)
        card.set_valign(Gtk.Align.CENTER)
        card.set_size_request(140, 160)

        # Icon
        icon = Gtk.Image.new_from_icon_name(action["icon"], Gtk.IconSize.DIALOG)
        icon.set_pixel_size(64)
        icon.modify_fg(Gtk.StateType.NORMAL, Gdk.color_parse(action["color"]))

        # Label
        label = Gtk.Label(label=action["label"])
        label.modify_fg(Gtk.StateType.NORMAL, Gdk.color_parse(action["color"]))
        label.set_justify(Gtk.Justification.CENTER)
        label.set_margin_bottom(12)

        card.pack_start(icon, True, True, 0)
        card.pack_start(label, False, False, 0)

        self.add(card)

        # Styling
        self.modify_bg(Gtk.StateType.NORMAL, Gdk.color_parse(CARD_BG))
        self.set_border_width(0)

        # Events
        self.connect("enter-notify-event", self.on_enter)
        self.connect("leave-notify-event", self.on_leave)
        self.connect("button-press-event", self.on_click)
        self.set_events(
            Gdk.EventMask.ENTER_NOTIFY_MASK
            | Gdk.EventMask.LEAVE_NOTIFY_MASK
            | Gdk.EventMask.BUTTON_PRESS_MASK
        )

    def on_enter(self, widget, event):
        self.modify_bg(Gtk.StateType.NORMAL, Gdk.color_parse(CARD_HOVER))
        return True

    def on_leave(self, widget, event):
        self.modify_bg(Gtk.StateType.NORMAL, Gdk.color_parse(CARD_BG))
        return True

    def on_click(self, widget, event):
        if event.button == 1:
            self.execute_action()
        return True

    def execute_action(self):
        subprocess.Popen(self.action["cmd"], shell=True)
        self.window.close()


class LogoutWindow(Gtk.Window):
    def __init__(self):
        super().__init__(title="Session Menu")
        self.set_decorated(False)
        self.set_resizable(False)
        self.set_position(Gtk.WindowPosition.CENTER)
        self.set_keep_above(True)
        self.set_type_hint(Gdk.WindowTypeHint.DOCK)

        # Main container
        main_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=0)
        main_box.set_border_width(20)
        main_box.modify_bg(Gtk.StateType.NORMAL, Gdk.color_parse(BG_COLOR))

        # Cards row
        cards_box = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=16)
        cards_box.set_halign(Gtk.Align.CENTER)
        cards_box.set_valign(Gtk.Align.CENTER)

        for action in ACTIONS:
            card = LogoutCard(action, self)
            cards_box.pack_start(card, False, False, 0)

        main_box.pack_start(cards_box, True, True, 0)
        self.add(main_box)

        # Style window
        self.modify_bg(Gtk.StateType.NORMAL, Gdk.color_parse(BG_COLOR))

        # Connect events
        self.connect("destroy", Gtk.main_quit)
        self.connect("key-press-event", self.on_key_press)

        # Set window size
        self.set_size_request(780, 220)

    def on_key_press(self, widget, event):
        key = event.keyval
        # Number keys 1-5
        if key in [Gdk.KEY_1, Gdk.KEY_KP_1]:
            ACTIONS[0]["cmd"] and self.execute_cmd(ACTIONS[0]["cmd"])
        elif key in [Gdk.KEY_2, Gdk.KEY_KP_2]:
            self.execute_cmd(ACTIONS[1]["cmd"])
        elif key in [Gdk.KEY_3, Gdk.KEY_KP_3]:
            self.execute_cmd(ACTIONS[2]["cmd"])
        elif key in [Gdk.KEY_4, Gdk.KEY_KP_4]:
            self.execute_cmd(ACTIONS[3]["cmd"])
        elif key in [Gdk.KEY_5, Gdk.KEY_KP_5]:
            self.execute_cmd(ACTIONS[4]["cmd"])
        elif key == Gdk.KEY_Escape:
            self.close()
        return True

    def execute_cmd(self, cmd):
        subprocess.Popen(cmd, shell=True)
        self.close()


if __name__ == "__main__":
    # Apply CSS with theme colors
    css = f"""
    window {{
        background-color: {BG_COLOR};
        border-radius: 2px;
        border: 2px solid {BORDER_COLOR};
    }}
    """
    style_provider = Gtk.CssProvider()
    style_provider.load_from_data(css.encode())
    Gtk.StyleContext.add_provider_for_screen(
        Gdk.Screen.get_default(),
        style_provider,
        Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION,
    )

    window = LogoutWindow()
    window.show_all()
    Gtk.main()
